import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#6a5d50",
        "tertiary-fixed-dim": "#efdccc",
        "tertiary-dim": "#5e5144",
        "on-secondary-fixed": "#3c4044",
        "tertiary-container": "#feebda",
        "surface-container": "#eeeeed",
        background: "#fbf9f8",
        "error-dim": "#4e0309",
        "on-tertiary-container": "#635649",
        "inverse-surface": "#0e0e0e",
        "secondary-fixed-dim": "#d1d5da",
        secondary: "#5b5f64",
        "on-tertiary-fixed": "#504438",
        "surface-tint": "#5f5e5e",
        "error-container": "#fe8983",
        "on-background": "#303333",
        "primary-dim": "#535252",
        "on-error-container": "#752121",
        "secondary-container": "#dfe3e8",
        "outline-variant": "#b1b2b2",
        "primary-fixed": "#e5e2e1",
        error: "#9f403d",
        "inverse-on-surface": "#9e9d9c",
        "primary-container": "#e5e2e1",
        "surface-container-low": "#f5f3f3",
        "on-surface-variant": "#5d5f60",
        "secondary-dim": "#4f5358",
        "on-error": "#fff7f6",
        "surface-bright": "#fbf9f8",
        primary: "#5f5e5e",
        "on-tertiary": "#fff7f3",
        "surface-container-highest": "#e2e2e3",
        "on-secondary-fixed-variant": "#585c61",
        "on-secondary-container": "#4e5257",
        "on-tertiary-fixed-variant": "#6e6053",
        "surface-dim": "#d9dada",
        "surface-variant": "#e2e2e3",
        outline: "#797b7b",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#303333",
        "on-primary-container": "#525151",
        "on-secondary": "#f6f9ff",
        "on-primary-fixed": "#403f3f",
        "surface-container-high": "#e8e8e8",
        "primary-fixed-dim": "#d7d4d3",
        "on-primary": "#faf7f6",
        "tertiary-fixed": "#feebda",
        "on-primary-fixed-variant": "#5c5b5b",
        surface: "#fbf9f8",
        "inverse-primary": "#ffffff",
        "secondary-fixed": "#dfe3e8",
      },
      fontFamily: {
        headline: ["var(--font-epilogue)"],
        body: ["var(--font-manrope)"],
        label: ["var(--font-manrope)"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [forms],
};

export default config;
